= Agent Installation - SoleAgent

== LM-Studio ==
- Start LM-Studio first.
- Select "_discover_" (-> the symbol magnifier lens) and use Model Search. Select a model from the list and download it (green button "Download" at bottom right)
- Download at least one LLM (`google/gemma-3-4b`) to local device.
- At LM-Studio select green terminal sign to the left - the green developer logs are visible.

== Sole-Agent Project

- Move to directory [mac] `/myprojects` or [win] `c:\myprojects`
- Execute `git clone https://github.com/agentic-ai-realm/sole-agent.git`
- Execute `cd sole-agent`
- Execute `uv venv .venv --python 3.12`
- Execute [mac] `source .venv/script/activate` or [win] `.\.venv\Scripts\activate`
- Execute `uv pip install corelibs`
- Execute `uv sync --active`
- Execute `uv lock`
- Open IDE at root [mac] `/myprojects/sole-agent`
- At IDE on project root [win] `/myprojects/sole-agent` or `c:\myprojects\sole-agent` go to file `main.py` and start processing (`run main`) or on terminal command line execute [mac] `python ./main.py` or [win] `python .\main.py` (when `python` is version >=3.11 ) - Watch the developer logs at LM-Studio.
- Processing takes a bit of time (LM-Studio needs to prepare llm)  - *Enjoy result!*

== Corelibs Update ==

Update the `corelibs` after source code changes inside the library here at the `Sole-Agent` project by terminal command sequence:
```
uv remove corelibs
uv add "corelibs @ file:///../corelibs/dist/corelibs-0.0.0-py3-none-any.whl"
uv lock --refresh
```


