= CORE Installation

- Recap: In last section clicking the green button "<> Code", then select "Download ZIP" and the ZIP file download started.

- Now create a directory `/myprojects/core-lib` or `c:\myprojects\core-lib`

- Extract the content of the ZIP file to `/myprojects/core-lib` or `c:\myprojects\core-lib`

- Change name of `pyproject.toml` to `pyproject.toml_bak`

- Change name of `poetry.lock` to `poetry.lock_bak`

- Execute: `touch pyproject.toml` or on windows powershell `New-item -Itemtype File pyproject.toml`

- Copy the content from github file  `introductory/core/pyproject.toml`, open file `pyproject.toml` and paste the content, then save it (location: `/myprojects/core-lib/pyproject.toml` or `c:\myprojects\core-lib\pyproject.toml`)

- Execute `uv venv .venv --python 3.12`

- Execute `./.venv/script/activate` or `.\.venv\Scripts\activate`

- Execute: `uv sync --active`

- Execute: `uv lock`

- Execute: `uv build`

- Validate - dist directory is created with content one
 `*.whl` and one `*tar.gz` file.
